spring:
  datasource:
    username: hospital_housekeeping
    password: hospital_housekeeping
    url: jdbc:mysql://localhost:3306/hospital_housekeeping
  
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true
   
   
  sql:
    init:
      mode: never
      